### ISSUE TITLE
[Bug Report] 1.20.1 config file naming log error

### ISSUE THREAD

**Issue by maevius669** [AdyTech99/HealthIndicators#7]
**Describe the bug**
error on launch
```
[Render thread/INFO]: Deserializing ModConfig from '/home/maevius/Apps/PrismLauncher/instances/[ModPack] Beauté 1.20.1/.minecraft/config/health_indicators_config.json'
[Render thread/INFO]: [STDERR]: java.io.FileNotFoundException: /home/maevius/Apps/PrismLauncher/instances/[ModPack] Beauté 1.20.1/.minecraft/config/healthindicators.json (No such file or directory)
[Render thread/INFO]: [STDERR]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[Render thread/INFO]: [STDERR]: 	at java.base/java.io.FileInputStream.open(Unknown Source)
[Render thread/INFO]: [STDERR]: 	at java.base/java.io.FileInputStream.<init>(Unknown Source)
[Render thread/INFO]: [STDERR]: 	at java.base/java.io.FileReader.<init>(Unknown Source)
[Render thread/INFO]: [STDERR]: 	at io.github.adytech99.healthindicators.config.Config.load(Config.java:40)
[Render thread/INFO]: [STDERR]: 	at io.github.adytech99.healthindicators.HealthIndicatorsMod.onInitializeClient(HealthIndicatorsMod.java:64)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:458)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:211)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[Render thread/INFO]: Never be heartless!
```
**Expected behavior**
File 'health_indicators_config.json' already exists but i always create a duplicate so i wont get that error (i just dont like errors 🤡)

**Desktop (please complete the following information):**
 - Minecraft Version: [1.20.1]
 - Java Version [17]
 - Mod Version [2.5.7]

**Additional context**
Also would it be possible to backport current 1.21 to 1.20.1?
This is an amazing mod and other mods dont even offer the half of what you do 🎉

**Comment by AdyTech99** [comment]
Is there any gameplay issue that this error creates? Like the config not saving?

**Comment by maevius669** [comment]
no other issues no

**Comment by maevius669** [comment]
just noticed this is also happening with 1.21

**Comment by AdyTech99** [comment]
> just noticed this is also happening with 1.21

In that case, it is probably caused by a mod conflict, considering that I can't reproduce it on my end.
Also, if it isn't accompanied by any actual game-play issue, what exactly do you want "fixed"?

**Comment by maevius669** [comment]
issue is caused by cardinal components api
changing `log-deserialization-warnings` to `false` resolved this for me
